# Generated by Django 3.2.7 on 2021-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mobile phone', 'mobile phone'), ('IPad', 'IPad'), ('Tablet', 'Tablet'), ('playstation', 'playstation'), ('X-Box', 'X-Box'), ('PCs', 'PCs'), ('watch', 'watch'), ('PC Accessories', 'PC Accessories'), ('fitness tools', 'fitness tools'), ('clothes', 'clothes'), ('Make ups', 'Make ups'), ('Furnitures', 'Furnitures')], max_length=50),
        ),
    ]
