# Generated by Django 3.2.5 on 2021-10-12 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20210930_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Cat_type',
            field=models.CharField(choices=[('techs', 'techs'), ('fitness tools', 'fitness tools'), ('clothes', 'clothes'), ('Make ups', 'Make ups'), ('Furnitures', 'Furnitures')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.save_comments_images)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
