# Generated by Django 3.2.5 on 2021-10-12 16:33

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211012_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_image',
            field=models.ImageField(default='media/defaults/user-icon.png', upload_to=products.models.save_comments_images),
        ),
    ]
